# Generated by Django 4.0 on 2021-12-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_birth_date_user_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
