# Generated by Django 3.2.5 on 2021-12-17 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_latitude', models.IntegerField()),
                ('st_longitude', models.IntegerField()),
                ('station', models.CharField(max_length=50)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linesStops.lines')),
            ],
        ),
    ]
