# Generated by Django 4.0 on 2021-12-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linesStops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='st_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stations',
            name='st_longitude',
            field=models.FloatField(),
        ),
    ]
