# Generated by Django 3.2.9 on 2021-12-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linesStops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_cord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='stations',
            name='st_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stations',
            name='st_longitude',
            field=models.FloatField(),
        ),
    ]
