# Generated by Django 3.2.9 on 2021-12-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linesStops', '0002_auto_20211221_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line_cord',
            old_name='latitude',
            new_name='LineCords',
        ),
        migrations.RemoveField(
            model_name='line_cord',
            name='longitude',
        ),
        migrations.AddField(
            model_name='line_cord',
            name='Color',
            field=models.CharField(default='red', max_length=50),
        ),
    ]
