# Generated by Django 3.2.9 on 2021-12-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linesStops', '0003_auto_20211221_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line_cord',
        ),
    ]
