# Generated by Django 3.2.9 on 2021-12-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linesStops', '0004_delete_line_cord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_cord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineCords', models.FloatField()),
                ('Color', models.CharField(default='red', max_length=50)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linesStops.lines')),
            ],
        ),
    ]
