# Generated by Django 3.2.9 on 2021-12-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linesStops', '0002_alter_stations_st_latitude_and_more'),
        ('linesStops', '0008_alter_line_cord_linecords'),
    ]

    operations = [
    ]
