# Generated by Django 4.0 on 2021-12-26 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('bus_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('operating', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapapi.driver')),
            ],
        ),
    ]
